# Site Settings
title: My Tech Blog
description: Troubleshooting and IT fixes.

# My Blog
baseurl: "/Blog" 
url: "https://shadowpbx.github.io"

# Build Settings
theme: minima
future: true
timezone: America/New_York

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
